import Link from "next/link";
import type { InheritanceReviewableText } from "@/lib/inheritance-certificate-data";
import { contactData } from "@/lib/home-data";
import { ReviewNote } from "./ReviewNote";

type Data = typeof import("@/lib/inheritance-certificate-data").inheritanceCertificateData;

function SectionHeading({ eyebrow, title, id }: { eyebrow: string; title: string; id: string }) {
  return <><p className="text-xs uppercase tracking-[0.18em] text-muted-foreground">{eyebrow}</p><h2 className="mt-4 font-display text-4xl leading-tight tracking-[-0.045em] text-foreground sm:text-5xl" id={id}>{title}</h2></>;
}

function ReviewableParagraph({ content, className = "" }: { content: InheritanceReviewableText; className?: string }) {
  return <p className={className} data-requires-legal-review={content.requiresLegalReview ? "true" : undefined}>{content.text}</p>;
}

export function InheritanceHero({ hero }: { hero: Data["hero"] }) {
  return <section className="mx-auto grid max-w-[1280px] gap-14 px-5 pb-[calc(8rem+env(safe-area-inset-bottom))] pt-16 sm:pb-24 sm:pt-24 lg:grid-cols-[minmax(0,1.15fr)_minmax(260px,0.85fr)] lg:items-end lg:gap-20 lg:px-8 lg:pb-32 lg:pt-28" aria-labelledby="inheritance-certificate-title"><div><p className="mb-6 text-xs uppercase tracking-[0.18em] text-muted-foreground">{hero.eyebrow}</p><h1 className="max-w-4xl font-display text-5xl leading-[0.98] tracking-[-0.055em] text-foreground sm:text-6xl lg:text-8xl" id="inheritance-certificate-title">{hero.title}</h1><p className="mt-8 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg sm:leading-8">{hero.description}</p><div className="mt-0 flex flex-col items-start gap-2 sm:mt-10 sm:flex-row sm:items-center sm:gap-4"><a className="border border-foreground bg-foreground px-5 py-3 text-sm text-background transition-colors hover:bg-transparent hover:text-foreground" href="#dokumenty">{hero.primaryCta}</a><a className="text-sm text-foreground underline decoration-border underline-offset-8 transition-colors hover:decoration-foreground" href="#wizyta">{hero.secondaryCta} <span aria-hidden="true">↓</span></a></div><p className="mt-8 text-xs uppercase tracking-[0.15em] text-muted-foreground">Wrocław <span className="px-2 text-olive">·</span> spadek · dokument · rejestr</p></div><div className="relative min-h-64 border-l border-border pl-8 sm:min-h-80 lg:min-h-[25rem] lg:pl-12" aria-hidden="true" data-editorial-mark><span className="absolute left-[-5px] top-0 size-2 rounded-full bg-olive" /><div className="flex h-full flex-col justify-between"><div className="pt-2"><p className="font-display text-7xl leading-[0.78] tracking-[-0.1em] text-foreground/80 sm:text-8xl">APD</p><div className="mt-6 flex items-center gap-4 sm:mt-8"><span className="h-px w-12 bg-border sm:w-16" /><p className="font-display text-6xl leading-[0.82] tracking-[-0.09em] text-foreground/80 sm:text-7xl">spadek</p></div></div><div className="space-y-3 text-xs uppercase tracking-[0.16em] text-muted-foreground"><div className="h-px w-20 bg-border" /><p>Wrocław / {new Date().getFullYear()}</p><p>Osoba · dokument · potwierdzenie</p></div></div></div></section>;
}

export function InheritanceParticipants({ content }: { content: Data["participants"] }) {
  return <section className="service-section border-t border-border pt-10" id="uczestnicy" aria-labelledby="participants-title"><SectionHeading eyebrow={content.eyebrow} title={content.title} id="participants-title" /><ReviewableParagraph content={content.answer} className="mt-6 max-w-2xl text-base leading-8 text-foreground/85" /><div className="mt-12 border-t border-border pt-8"><h3 className="font-display text-3xl tracking-[-0.03em] text-foreground">{content.togetherTitle}</h3><ReviewableParagraph content={content.togetherText} className="mt-4 max-w-2xl text-sm leading-7 text-muted-foreground" /><ReviewNote className="mt-4" /></div></section>;
}

export function InheritanceDocuments({ content }: { content: Data["documents"] }) {
  return <section className="service-section border-t border-border pt-10" id="dokumenty" aria-labelledby="inheritance-documents-title"><SectionHeading eyebrow={content.eyebrow} title={content.title} id="inheritance-documents-title" /><ReviewableParagraph content={content.intro} className="mt-6 max-w-2xl text-base leading-7 text-muted-foreground" /><ReviewNote className="mt-4" /><div className="mt-10 border-t border-border">{content.statutoryItems.map((item) => <div className="grid gap-2 border-b border-border py-5 sm:grid-cols-[5.5rem_0.8fr_1.2fr] sm:gap-6" key={item.number}><span className="font-mono text-xs text-muted-foreground">{item.number}</span><h3 className="text-base font-medium text-foreground">{item.title}</h3><ReviewableParagraph content={item.text} className="text-sm leading-6 text-muted-foreground" /></div>)}</div><div className="mt-12 border-t border-border pt-8"><h3 className="font-display text-3xl tracking-[-0.03em] text-foreground">{content.additionalTitle}</h3><ul className="mt-5 space-y-3 border-t border-border pt-5">{content.additionalItems.map((item) => <li className="flex gap-3 text-sm leading-7 text-muted-foreground" data-requires-legal-review="true" key={item.text}><span className="text-olive" aria-hidden="true">·</span><span>{item.text}</span></li>)}</ul><ReviewNote className="mt-4" /></div><a className="mt-8 inline-flex border-b border-foreground pb-2 text-sm text-foreground" href="#wizyta">{content.cta} <span className="ml-3" aria-hidden="true">→</span></a></section>;
}

export function InheritanceTestament({ content }: { content: Data["testament"] }) {
  return <section className="service-section border-t border-border pt-10" id="testament" aria-labelledby="testament-title"><SectionHeading eyebrow={content.eyebrow} title={content.title} id="testament-title" /><ReviewableParagraph content={content.answer} className="mt-6 max-w-2xl text-base leading-8 text-foreground/85" /></section>;
}

export function InheritanceSixMonths({ content }: { content: Data["sixMonths"] }) {
  return <section className="service-section border-t border-border bg-surface px-5 py-10 sm:px-8" id="szesc-miesiecy" aria-labelledby="six-months-title"><div className="mx-auto max-w-[1280px]"><SectionHeading eyebrow={content.eyebrow} title={content.title} id="six-months-title" /><ReviewableParagraph content={content.answer} className="mt-6 max-w-2xl text-base leading-8 text-foreground/85" /></div></section>;
}

export function InheritanceObstacles({ content }: { content: Data["obstacles"] }) {
  return <section className="service-section border-t border-border pt-10" id="przeszkody" aria-labelledby="obstacles-title"><SectionHeading eyebrow={content.eyebrow} title={content.title} id="obstacles-title" /><ReviewableParagraph content={content.intro} className="mt-6 max-w-2xl text-base leading-7 text-muted-foreground" /><ReviewNote className="mt-4" /><ul className="mt-10 border-t border-border">{content.items.map((item, index) => <li className="flex gap-5 border-b border-border py-5 text-sm leading-7 text-muted-foreground" data-requires-legal-review="true" key={item.text}><span className="font-mono text-xs text-muted-foreground">0{index + 1}</span><span>{item.text}</span></li>)}</ul></section>;
}

export function InheritanceEffects({ content }: { content: Data["effects"] }) {
  return <section className="service-section border-t border-border pt-10" id="skutki" aria-labelledby="effects-title"><SectionHeading eyebrow={content.eyebrow} title={content.title} id="effects-title" /><ReviewableParagraph content={content.answer} className="mt-6 max-w-2xl text-base leading-8 text-foreground/85" /><div className="mt-12 border-l border-olive pl-5"><h3 className="font-display text-2xl tracking-[-0.03em] text-foreground">{content.registerTitle}</h3><ReviewableParagraph content={content.registerText} className="mt-3 max-w-2xl text-sm leading-7 text-muted-foreground" /></div></section>;
}

export function InheritanceAfterApd({ content }: { content: Data["afterApd"] }) {
  return <section className="service-section border-t border-border pt-10" id="co-dalej" aria-labelledby="after-apd-title"><SectionHeading eyebrow={content.eyebrow} title={content.title} id="after-apd-title" /><ReviewableParagraph content={content.intro} className="mt-6 max-w-2xl text-base leading-7 text-muted-foreground" /><ReviewNote className="mt-4" /><div className="mt-10 grid gap-x-8 border-t border-border sm:grid-cols-2">{content.items.map((item) => <article className="border-b border-border py-6" key={item.title}><h3 className="font-display text-2xl tracking-[-0.03em] text-foreground">{item.title}</h3><ReviewableParagraph content={item.text} className="mt-3 text-sm leading-6 text-muted-foreground" /></article>)}</div><div className="mt-12 border-l border-olive pl-5"><h3 className="font-display text-2xl tracking-[-0.03em] text-foreground">{content.sdz2Title}</h3><ReviewableParagraph content={content.sdZ2Text} className="mt-3 text-sm leading-7 text-muted-foreground" /><ReviewNote className="mt-4" /></div></section>;
}

export function InheritanceCosts({ content }: { content: Data["costs"] }) {
  return <section className="service-section border-t border-border pt-10" id="koszty" aria-labelledby="inheritance-costs-title"><SectionHeading eyebrow={content.eyebrow} title={content.title} id="inheritance-costs-title" /><ReviewableParagraph content={content.intro} className="mt-6 max-w-2xl text-base leading-7 text-muted-foreground" /><ReviewNote className="mt-4" /><div className="mt-10 border-t border-border">{content.items.map((item, index) => <div className="grid gap-2 border-b border-border py-5 sm:grid-cols-[5.5rem_1fr_auto] sm:items-baseline sm:gap-6" key={item.label}><span className="font-mono text-xs text-muted-foreground">0{index + 1}</span><h3 className="text-sm font-medium text-foreground">{item.label}</h3><p className="text-sm text-muted-foreground" data-requires-legal-review="true">{item.amount}</p></div>)}</div><p className="mt-6 max-w-2xl border-l border-olive pl-4 text-sm leading-7 text-muted-foreground" data-requires-legal-review="true">{content.registerFee.text}</p><ReviewNote className="mt-4" /></section>;
}

export function InheritanceContactCta({ contact }: { contact: Data["contact"] }) {
  return <section className="service-section border-t border-border pt-10" id="wizyta" aria-labelledby="inheritance-contact-title"><div className="grid gap-10 border-b border-border pb-16 sm:pb-20 lg:grid-cols-[1fr_0.75fr] lg:gap-20"><div><p className="text-xs uppercase tracking-[0.18em] text-muted-foreground">{contact.eyebrow}</p><h2 className="mt-4 max-w-xl font-display text-4xl leading-tight tracking-[-0.045em] text-foreground sm:text-5xl" id="inheritance-contact-title">{contact.title}</h2><p className="mt-6 max-w-xl text-base leading-7 text-muted-foreground">{contact.description}</p><div className="mt-8 flex flex-col items-start gap-4 sm:flex-row sm:items-center"><a className="border border-foreground bg-foreground px-5 py-3 text-sm text-background transition-colors hover:bg-transparent hover:text-foreground" href="#kontakt">Zapytaj kancelarię</a><Link className="text-sm text-foreground underline decoration-border underline-offset-8" href="/">Wróć na stronę główną</Link></div></div><div className="border-t border-border pt-6 lg:border-l lg:border-t-0 lg:pl-10"><p className="text-xs uppercase tracking-[0.18em] text-muted-foreground">Kontakt</p><div className="mt-6 space-y-5 text-sm leading-6" id="kontakt"><div><p className="text-muted-foreground">Adres</p><p className="mt-1 text-foreground">{contactData.address}</p></div><div><p className="text-muted-foreground">Parking</p><p className="mt-1 text-foreground">{contactData.parking}</p></div></div></div></div></section>;
}
