import type { OccasionalLeaseReviewableText } from "@/lib/occasional-lease-data";
import { ReviewNote } from "./ReviewNote";

type Data = typeof import("@/lib/occasional-lease-data").occasionalLeaseData;

function SectionHeading({ eyebrow, title, id }: { eyebrow: string; title: string; id: string }) {
  return <><p className="text-xs uppercase tracking-[0.18em] text-muted-foreground">{eyebrow}</p><h2 className="mt-4 font-display text-4xl leading-tight tracking-[-0.045em] text-foreground sm:text-5xl" id={id}>{title}</h2></>;
}

function ReviewableParagraph({ content, className = "" }: { content: OccasionalLeaseReviewableText; className?: string }) {
  return <p className={className} data-requires-legal-review={content.requiresLegalReview ? "true" : undefined}>{content.text}</p>;
}

export function OccasionalLeaseHero({ hero }: { hero: Data["hero"] }) {
  return <section className="mx-auto grid max-w-[1280px] gap-14 px-5 pb-20 pt-16 sm:pb-24 sm:pt-24 lg:grid-cols-[minmax(0,1.15fr)_minmax(260px,0.85fr)] lg:items-end lg:gap-20 lg:px-8 lg:pb-32 lg:pt-28" aria-labelledby="occasional-lease-title"><div><p className="mb-6 text-xs uppercase tracking-[0.18em] text-muted-foreground">{hero.eyebrow}</p><h1 className="max-w-4xl font-display text-5xl leading-[0.98] tracking-[-0.055em] text-foreground sm:text-6xl lg:text-8xl" id="occasional-lease-title">{hero.title}</h1><p className="mt-8 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg sm:leading-8">{hero.description}</p><div className="mt-10 flex flex-col items-start gap-4 sm:flex-row sm:items-center"><a className="border border-foreground bg-foreground px-5 py-3 text-sm text-background transition-colors hover:bg-transparent hover:text-foreground" href="#dokumenty">{hero.primaryCta}</a><a className="text-sm text-foreground underline decoration-border underline-offset-8 transition-colors hover:decoration-foreground" href="#wizyta">{hero.secondaryCta} <span aria-hidden="true">↓</span></a></div><p className="mt-8 text-xs uppercase tracking-[0.15em] text-muted-foreground">Wrocław <span className="px-2 text-olive">·</span> najem · oświadczenie · lokal</p></div><div className="relative min-h-64 border-l border-border pl-8 sm:min-h-80 lg:min-h-[25rem] lg:pl-12" aria-hidden="true" data-editorial-mark><span className="absolute left-[-5px] top-0 size-2 rounded-full bg-olive" /><div className="flex h-full flex-col justify-between"><div className="pt-2"><p className="font-display text-7xl leading-[0.78] tracking-[-0.1em] text-foreground/80 sm:text-8xl">najemca</p><div className="mt-6 flex items-center gap-4 sm:mt-8"><span className="h-px w-12 bg-border sm:w-16" /><p className="font-display text-5xl leading-[0.82] tracking-[-0.09em] text-foreground/80 sm:text-6xl">właściciel</p></div></div><div className="space-y-3 text-xs uppercase tracking-[0.16em] text-muted-foreground"><div className="h-px w-20 bg-border" /><p>Wrocław / {new Date().getFullYear()}</p><p>Umowa · oświadczenie · zgłoszenie</p></div></div></div></section>;
}

export function OccasionalLeaseEligibility({ content }: { content: Data["eligibility"] }) {
  return <section className="service-section border-t border-border pt-10" id="dla-kogo" aria-labelledby="eligibility-title"><SectionHeading eyebrow={content.eyebrow} title={content.title} id="eligibility-title" /><ReviewableParagraph content={content.intro} className="mt-6 max-w-2xl text-base leading-8 text-foreground/85" /><div className="mt-10 border-t border-border">{content.items.map((item, index) => <div className="grid gap-2 border-b border-border py-5 sm:grid-cols-[5.5rem_0.8fr_1.2fr] sm:gap-6" key={item.title}><span className="font-mono text-xs text-muted-foreground">{String(index + 1).padStart(2, "0")}</span><h3 className="text-base font-medium text-foreground">{item.title}</h3><ReviewableParagraph content={item.text} className="text-sm leading-6 text-muted-foreground" /></div>)}</div><ReviewableParagraph content={content.note} className="mt-8 border-l border-olive pl-4 text-sm leading-7 text-muted-foreground" /></section>;
}

export function OccasionalLeaseRoles({ content }: { content: Data["roles"] }) {
  return <section className="service-section border-t border-border pt-10" id="uczestnicy" aria-labelledby="roles-title"><SectionHeading eyebrow={content.eyebrow} title={content.title} id="roles-title" /><div className="mt-10 grid border-y border-border sm:grid-cols-2"><div className="border-b border-border py-8 sm:border-b-0 sm:border-r sm:pr-8"><p className="text-xs uppercase tracking-[0.18em] text-muted-foreground">01</p><h3 className="mt-4 font-display text-3xl tracking-[-0.03em] text-foreground">{content.tenant.title}</h3><ReviewableParagraph content={content.tenant.text} className="mt-4 text-sm leading-7 text-muted-foreground" /></div><div className="py-8 sm:pl-8"><p className="text-xs uppercase tracking-[0.18em] text-muted-foreground">02</p><h3 className="mt-4 font-display text-3xl tracking-[-0.03em] text-foreground">{content.owner.title}</h3><ReviewableParagraph content={content.owner.text} className="mt-4 text-sm leading-7 text-muted-foreground" /></div></div><ReviewableParagraph content={content.presence} className="mt-6 max-w-2xl text-xs leading-6 text-muted-foreground" /><ReviewNote className="mt-4" /></section>;
}

export function OccasionalLeaseDocuments({ content }: { content: Data["documents"] }) {
  return <section className="service-section border-t border-border pt-10" id="dokumenty" aria-labelledby="documents-title"><SectionHeading eyebrow={content.eyebrow} title={content.title} id="documents-title" /><ReviewableParagraph content={content.intro} className="mt-6 max-w-2xl text-base leading-7 text-muted-foreground" /><ReviewNote className="mt-4" /><div className="mt-10 border-t border-border">{content.statutory.map((item, index) => <div className="grid gap-2 border-b border-border py-5 sm:grid-cols-[5.5rem_0.8fr_1.2fr] sm:gap-6" key={item.title}><span className="font-mono text-xs text-muted-foreground">{String(index + 1).padStart(2, "0")}</span><h3 className="text-base font-medium text-foreground">{item.title}</h3><ReviewableParagraph content={item.text} className="text-sm leading-6 text-muted-foreground" /></div>)}</div><div className="mt-12 border-t border-border pt-8"><h3 className="font-display text-3xl tracking-[-0.03em] text-foreground">{content.confirmationTitle}</h3><ul className="mt-5 space-y-3 border-t border-border pt-5">{content.confirmation.map((item) => <li className="flex gap-3 text-sm leading-7 text-muted-foreground" data-requires-legal-review="true" key={item.text}><span className="text-olive" aria-hidden="true">·</span><span>{item.text}</span></li>)}</ul><ReviewNote className="mt-4" /></div><a className="mt-8 inline-flex border-b border-foreground pb-2 text-sm text-foreground" href="#wizyta">{content.cta} <span className="ml-3" aria-hidden="true">→</span></a></section>;
}

export function OccasionalLeaseOtherLocale({ content }: { content: Data["otherLocale"] }) {
  return <section className="service-section border-t border-border pt-10" id="inny-lokal" aria-labelledby="other-locale-title"><SectionHeading eyebrow={content.eyebrow} title={content.title} id="other-locale-title" /><ReviewableParagraph content={content.answer} className="mt-6 max-w-2xl text-base leading-8 text-foreground/85" /><div className="mt-12 border-t border-border pt-8"><h3 className="font-display text-3xl tracking-[-0.03em] text-foreground">{content.consentTitle}</h3><ReviewableParagraph content={content.consent} className="mt-4 max-w-2xl text-sm leading-7 text-muted-foreground" /></div></section>;
}

export function OccasionalLeaseReplacement({ content }: { content: Data["replacementLocale"] }) {
  return <section className="service-section border-t border-border pt-10" id="21-dni" aria-labelledby="replacement-title"><SectionHeading eyebrow={content.eyebrow} title={content.title} id="replacement-title" /><ReviewableParagraph content={content.answer} className="mt-6 max-w-2xl text-base leading-8 text-foreground/85" /><ReviewableParagraph content={content.note} className="mt-8 border-l border-olive pl-4 text-sm leading-7 text-muted-foreground" /></section>;
}

export function OccasionalLeaseTaxOffice({ content }: { content: Data["taxOffice"] }) {
  return <section className="service-section border-t border-border pt-10" id="urzad-skarbowy" aria-labelledby="tax-office-title"><SectionHeading eyebrow={content.eyebrow} title={content.title} id="tax-office-title" /><p className="mt-8 font-display text-7xl leading-none tracking-[-0.07em] text-foreground sm:text-8xl">{content.direct}</p><ReviewableParagraph content={content.answer} className="mt-6 max-w-2xl text-base leading-8 text-foreground/85" /><ReviewableParagraph content={content.consequence} className="mt-8 max-w-2xl border-l border-olive pl-4 text-sm leading-7 text-muted-foreground" /></section>;
}

export function OccasionalLeaseEnforcement({ content }: { content: Data["enforcement"] }) {
  return <section className="service-section border-t border-border pt-10" id="procedura" aria-labelledby="enforcement-title"><SectionHeading eyebrow={content.eyebrow} title={content.title} id="enforcement-title" /><ReviewableParagraph content={content.answer} className="mt-6 max-w-2xl text-base leading-8 text-foreground/85" /><ol className="mt-10 border-t border-border">{content.steps.map((step, index) => <li className="grid gap-3 border-b border-border py-6 sm:grid-cols-[5.5rem_1fr] sm:gap-6" key={step.text}><span className="font-mono text-sm text-muted-foreground">{String(index + 1).padStart(2, "0")}</span><ReviewableParagraph content={step} className="text-sm leading-7 text-muted-foreground" /></li>)}</ol></section>;
}

export function OccasionalLeaseCosts({ content }: { content: Data["costs"] }) {
  return <section className="service-section border-t border-border pt-10" id="koszt" aria-labelledby="cost-title"><SectionHeading eyebrow={content.eyebrow} title={content.title} id="cost-title" /><ReviewableParagraph content={content.intro} className="mt-6 max-w-2xl text-base leading-7 text-muted-foreground" /><div className="mt-10 grid gap-6 border-y border-border py-8 sm:grid-cols-2"><div><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">Limit w {content.year} r.</p><p className="mt-3 font-display text-5xl tracking-[-0.05em] text-foreground">{content.feeLimit}</p><p className="mt-2 text-sm text-muted-foreground">1/10 minimalnego wynagrodzenia {content.minimumWage}</p></div><p className="text-sm leading-7 text-muted-foreground">To ustawowy limit wynagrodzenia za wskazane oświadczenie, a nie ponadczasowa cena całej wizyty.</p></div><ReviewableParagraph content={content.note} className="mt-6 max-w-2xl border-l border-olive pl-4 text-sm leading-7 text-muted-foreground" /></section>;
}

export function OccasionalLeaseContact({ contact }: { contact: Data["contact"] }) {
  return <section className="service-section border-t border-border pt-10" id="wizyta" aria-labelledby="occasional-contact-title"><div className="grid gap-10 border-b border-border pb-16 sm:pb-20 lg:grid-cols-[1fr_0.75fr] lg:gap-20"><div><p className="text-xs uppercase tracking-[0.18em] text-muted-foreground">{contact.eyebrow}</p><h2 className="mt-4 max-w-xl font-display text-4xl leading-tight tracking-[-0.045em] text-foreground sm:text-5xl" id="occasional-contact-title">{contact.title}</h2><p className="mt-6 max-w-xl text-base leading-7 text-muted-foreground">{contact.description}</p><div className="mt-8 flex flex-col items-start gap-4 sm:flex-row sm:items-center"><a className="border border-foreground bg-foreground px-5 py-3 text-sm text-background transition-colors hover:bg-transparent hover:text-foreground" href="#kontakt">Zapytaj kancelarię</a><a className="text-sm text-foreground underline decoration-border underline-offset-8" href="#top">Wróć na początek ↑</a></div></div><div className="border-t border-border pt-6 lg:border-l lg:border-t-0 lg:pl-10"><p className="text-xs uppercase tracking-[0.18em] text-muted-foreground">Kontakt</p><div className="mt-6 space-y-5 text-sm leading-6" id="kontakt"><div><p className="text-muted-foreground">Adres</p><p className="mt-1 text-foreground">ul. Mińska 54–56, Wrocław</p></div><div><p className="text-muted-foreground">Parking</p><p className="mt-1 text-foreground">Parking przy kancelarii</p></div></div></div></div></section>;
}
