import { Header } from "@/components/Header";
import { HomeComplete } from "@/components/HomeComplete";
import { HeroImagePlaceholder } from "@/components/HeroImagePlaceholder";
import { MobileStickyActions } from "@/components/MobileStickyActions";
import { ServiceSearch } from "@/components/ServiceSearch";
import { StructuredData } from "@/components/StructuredData";

const categories = [
  { number: "01", title: "Nieruchomości", items: ["Sprzedaż mieszkania", "Umowa przedwstępna", "Darowizna", "Hipoteka"], link: "Wszystkie sprawy związane z nieruchomościami" },
  { number: "02", title: "Spółki i biznes", items: ["Założenie spółki z o.o.", "Zmiana umowy spółki", "Sprzedaż udziałów", "Fundacja rodzinna"], link: "Spółki i przedsiębiorcy" },
  { number: "03", title: "Spadki", items: ["Akt poświadczenia dziedziczenia", "Testament", "Odrzucenie spadku", "Dział spadku"] },
  { number: "04", title: "Rodzina", items: ["Umowy majątkowe", "Darowizny", "Pełnomocnictwa"] },
];

const smallEntries = ["Najem okazjonalny", "Poświadczenia i pozostałe czynności"];

export default function Home() {
  return <div id="top" className="page-shell min-h-screen overflow-clip"><StructuredData /><Header /><main><section className="mx-auto max-w-[1280px] px-5 pb-20 pt-16 sm:pb-28 sm:pt-24 lg:px-8 lg:pb-32 lg:pt-20"><div className="grid items-center gap-14 lg:grid-cols-12 lg:gap-10"><div className="lg:col-span-6 lg:pr-8"><p className="intro-eyebrow mb-6 text-[11px] font-semibold uppercase tracking-[0.18em] text-olive">Kancelaria notarialna · Wrocław</p><h1 className="intro-heading max-w-[680px] font-display text-[48px] leading-[0.96] tracking-[-0.045em] sm:text-[62px] lg:text-[72px]">Ważne sprawy warto załatwić spokojnie.</h1><div className="intro-copy"><p className="mt-8 max-w-[640px] text-[16px] leading-7 text-foreground/70 sm:text-[18px] sm:leading-8">Maria Czarniak i Sara Podkówka prowadzą kancelarię notarialną na wrocławskim Muchoborze Wielkim. Pomagają w sprawach dotyczących nieruchomości, spółek, spadków oraz innych czynności notarialnych.</p><div className="mt-9 flex flex-col items-start gap-5 sm:flex-row sm:items-center"><a href="#sprawy" className="inline-flex min-h-12 items-center justify-center bg-foreground px-6 text-[13px] font-semibold text-surface transition-colors hover:bg-dark-olive">Sprawdź, czego potrzebujesz <span className="ml-4 text-base" aria-hidden="true">↗</span></a><a href="#wizyta" className="text-[13px] font-semibold text-foreground underline decoration-border underline-offset-8 transition-colors hover:decoration-olive">Umów wizytę</a></div><p className="mt-8 text-[11px] leading-5 text-foreground/70 sm:mt-7">Parking przy kancelarii <span className="px-2 text-olive">·</span> Terminy również w soboty</p></div></div><div className="lg:col-span-5 lg:col-start-8"><HeroImagePlaceholder /></div></div></section>

      <section id="sprawy" className="border-t border-border bg-surface"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:py-28 lg:px-8 lg:py-32"><div className="grid gap-12 lg:grid-cols-12 lg:gap-10"><div className="lg:col-span-4"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-olive">01 — Czynności</p><h2 className="mt-5 font-display text-[40px] leading-none tracking-[-0.04em] sm:text-[52px]">Co chcesz<br className="hidden sm:block" /> załatwić?</h2></div><div className="lg:col-span-7 lg:col-start-6"><p className="max-w-[650px] text-[16px] leading-7 text-foreground/70 sm:text-[18px] sm:leading-8">Znajdź swoją sprawę i sprawdź, jakie dokumenty przygotować, jak przebiega czynność oraz czego możesz spodziewać się przed wizytą.</p><div className="mt-14 grid gap-x-10 gap-y-0 sm:grid-cols-2">{categories.map((category) => <article id={category.number === "01" ? "sprzedaz-mieszkania" : undefined} key={category.number} className="group border-t border-border py-7"><div className="flex items-start justify-between gap-4"><span className="text-[12px] font-semibold text-foreground/70 transition-colors group-hover:text-olive">{category.number}</span><span className="text-foreground/70 transition-transform group-hover:translate-x-1" aria-hidden="true">↗</span></div><h3 className="mt-6 font-display text-[30px] leading-none tracking-[-0.03em]">{category.title}</h3><ul className="mt-5 space-y-2 text-[13px] text-foreground/70">{category.items.map((item) => <li key={item}>{item}</li>)}</ul>{category.link && <a href="#search" className="mt-6 inline-block text-[11px] font-semibold text-foreground underline decoration-border underline-offset-4 transition-colors hover:decoration-olive">{category.link} <span aria-hidden="true">↗</span></a>}</article>)}</div><div className="grid border-t border-border sm:grid-cols-2">{smallEntries.map((entry, index) => <a href="#search" key={entry} className="group flex items-center justify-between border-b border-border py-5 text-[14px] font-semibold sm:mr-5"><span><span className="mr-4 text-[11px] font-normal text-foreground/70 transition-colors group-hover:text-olive">0{index + 5}</span>{entry}</span><span className="text-foreground/70 transition-transform group-hover:translate-x-1" aria-hidden="true">↗</span></a>)}</div></div></div></div></section>

      <section id="search" className="border-t border-border"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:py-28 lg:px-8 lg:py-32"><div className="grid gap-10 lg:grid-cols-12"><div className="lg:col-span-5"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-olive">Nie musisz znać nazwy czynności</p><h2 className="mt-5 max-w-[530px] font-display text-[40px] leading-[0.98] tracking-[-0.04em] sm:text-[52px]">Opisz, czego potrzebujesz.</h2></div><div className="lg:col-span-7"><ServiceSearch /></div></div></div></section>

      <HomeComplete />
    </main><MobileStickyActions /></div>;
}
