import {
  businessServices,
  contactData,
  draftContentNote,
  footerLinks,
  knowledgeItems,
  practicalAdvantages,
  profiles,
  propertyQuestions,
  visitSteps,
} from "@/lib/home-data";
import { BrandWordmark } from "@/components/BrandWordmark";
import { sitePath } from "@/lib/site-config";

function Arrow() {
  return <span aria-hidden="true">↗</span>;
}

function ProfilePlaceholder({ imagePath, name }: { imagePath: string; name: string }) {
  return <div className="relative aspect-[4/5] overflow-hidden bg-secondary" data-image-placeholder={imagePath} role="img" aria-label={`Miejsce na fotografię: ${name}`}><div className="absolute inset-0 flex flex-col justify-between p-6 sm:p-8"><div className="flex items-center justify-between text-[10px] uppercase tracking-[0.18em] text-foreground/70"><span>Portret kancelarii</span><span aria-hidden="true">{imagePath.split("/").pop()}</span></div><div><div className="mb-5 h-px w-16 bg-olive/60" /><p className="font-display text-[34px] leading-none tracking-[-0.04em] text-foreground sm:text-[42px]">Miejsce na<br />fotografię.</p><p className="mt-5 max-w-[230px] text-[11px] leading-5 text-foreground/70">Docelowy plik: {imagePath}</p></div></div></div>;
}

export function HomeComplete() {
  return <>
    <section id="dokumenty" className="border-t border-border bg-surface"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:py-28 lg:px-8 lg:py-32"><div className="grid gap-12 lg:grid-cols-12 lg:gap-10"><div className="lg:col-span-4"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-olive">02 — Przygotowanie</p><h2 className="mt-5 max-w-[440px] font-display text-[40px] leading-[0.98] tracking-[-0.04em] sm:text-[52px]">Przygotuj się do wizyty.</h2></div><div className="lg:col-span-7 lg:col-start-6"><div className="divide-y divide-border border-t border-border">{visitSteps.map((step) => <div key={step.number} className="grid gap-4 py-6 sm:grid-cols-[72px_1fr] sm:gap-8"><span className="text-[12px] font-semibold text-olive">{step.number}</span><div><h3 className="font-display text-[28px] leading-none tracking-[-0.03em]">{step.title}</h3><p className="mt-3 max-w-[520px] text-[14px] leading-6 text-foreground/70">{step.description}</p></div></div>)}</div><a href="#search" className="mt-8 inline-flex items-center text-[13px] font-semibold text-foreground underline decoration-border underline-offset-8 transition-colors hover:decoration-olive">Sprawdź potrzebne dokumenty <span className="ml-3"><Arrow /></span></a></div></div></div></section>

    <section className="border-t border-border"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:py-28 lg:px-8 lg:py-32"><div className="grid gap-12 lg:grid-cols-12 lg:gap-10"><div className="lg:col-span-5 lg:pt-3"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-olive">Nieruchomości</p><h2 className="mt-5 max-w-[480px] font-display text-[48px] leading-[0.95] tracking-[-0.045em] sm:text-[64px]">Sprzedajesz mieszkanie?</h2><p className="mt-7 max-w-[430px] text-[16px] leading-7 text-foreground/70">Zbierz podstawowe informacje przed rozmową z kancelarią. Poniższe pytania pomagają uporządkować przygotowania bez zastępowania indywidualnej weryfikacji dokumentów.</p><a href={sitePath("/nieruchomosci/sprzedaz-mieszkania/")} className="mt-8 inline-flex items-center bg-foreground px-5 py-3 text-[12px] font-semibold text-surface transition-colors hover:bg-dark-olive">Przewodnik po sprzedaży mieszkania <span className="ml-4"><Arrow /></span></a></div><div className="lg:col-span-6 lg:col-start-7"><div className="divide-y divide-border border-y border-border">{propertyQuestions.map((item) => <article key={item.number} className="grid gap-4 py-6 sm:grid-cols-[48px_1fr] sm:gap-6"><span className="text-[12px] font-semibold text-olive">{item.number}</span><div><h3 className="max-w-[520px] font-display text-[26px] leading-[1.05] tracking-[-0.03em]">{item.question}</h3><p className="mt-3 max-w-[500px] text-[13px] leading-6 text-foreground/70">{item.answer}</p></div></article>)}</div></div></div></div></section>

    <section id="kancelaria" className="border-t border-border bg-surface"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:py-28 lg:px-8 lg:py-32"><div className="max-w-[660px]"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-olive">03 — Kancelaria</p><h2 className="mt-5 font-display text-[40px] leading-none tracking-[-0.04em] sm:text-[52px]">Dwie osoby. Spokojne przygotowanie.</h2><p className="mt-6 text-[15px] leading-7 text-foreground/70">{draftContentNote}</p></div><div className="mt-16 space-y-20 sm:mt-20 lg:space-y-28">{profiles.map((profile) => <article key={profile.name} className={`grid items-center gap-10 lg:grid-cols-12 lg:gap-16 ${profile.imageSide === "right" ? "lg:[&>div:first-child]:order-2" : ""}`}><div className="lg:col-span-5"><ProfilePlaceholder imagePath={profile.imagePath} name={profile.name} /></div><div className="lg:col-span-5 lg:col-start-7"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-olive">Profil roboczy</p><h3 className="mt-5 font-display text-[40px] leading-none tracking-[-0.04em] sm:text-[50px]">{profile.name}</h3><p className="mt-6 max-w-[560px] text-[16px] leading-7 text-foreground/70">{profile.description}</p><p className="mt-6 text-[11px] text-foreground/60">{draftContentNote}</p></div></article>)}</div></div></section>

    <section className="border-t border-border"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:py-28 lg:px-8 lg:py-32"><div className="grid gap-10 lg:grid-cols-12 lg:gap-10"><div className="lg:col-span-5"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-olive">04 — W praktyce</p><h2 className="mt-5 max-w-[480px] font-display text-[40px] leading-[0.98] tracking-[-0.04em] sm:text-[52px]">Dobrze wiedzieć przed wizytą.</h2></div><div className="lg:col-span-6 lg:col-start-7"><ul className="divide-y divide-border border-y border-border">{practicalAdvantages.map((item, index) => <li key={item} className="flex items-center justify-between gap-6 py-5 text-[16px]"><span><span className="mr-5 text-[11px] text-olive">0{index + 1}</span>{item}</span><span className="text-foreground/60" aria-hidden="true">↗</span></li>)}</ul></div></div></div></section>

    <section className="border-t border-border bg-secondary/50"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:py-28 lg:px-8 lg:py-32"><div className="grid gap-12 lg:grid-cols-12 lg:gap-10"><div className="lg:col-span-5"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-olive">Dla przedsiębiorców</p><h2 className="mt-5 max-w-[500px] font-display text-[40px] leading-[0.98] tracking-[-0.04em] sm:text-[52px]">Spółka zaczyna się od dobrej umowy.</h2></div><div className="lg:col-span-6 lg:col-start-7"><div className="grid border-y border-border sm:grid-cols-2">{businessServices.map((service, index) => <a href="#sprawy" key={service} className="group flex items-center justify-between border-b border-border py-5 text-[14px] font-semibold last:border-0 sm:mr-8"> <span><span className="mr-4 text-[11px] font-normal text-olive">0{index + 1}</span>{service}</span><span className="text-foreground/60 transition-transform group-hover:translate-x-1" aria-hidden="true">↗</span></a>)}</div><a href="#sprawy" className="mt-8 inline-flex items-center text-[13px] font-semibold text-foreground underline decoration-border underline-offset-8 transition-colors hover:decoration-olive">Spółki i biznes <span className="ml-3"><Arrow /></span></a></div></div></div></section>

    <section className="border-t border-border"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:py-28 lg:px-8 lg:py-32"><div className="grid gap-12 lg:grid-cols-12 lg:gap-10"><div className="lg:col-span-5"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-olive">05 — Baza wiedzy</p><h2 className="mt-5 max-w-[540px] font-display text-[40px] leading-[0.98] tracking-[-0.04em] sm:text-[52px]">Odpowiedzi na pytania, które pojawiają się przed wizytą.</h2></div><div className="lg:col-span-6 lg:col-start-7"><div className="divide-y divide-border border-y border-border">{knowledgeItems.map((item, index) => <a href="#wiedza" key={item.title} className="group block py-6"><div className="flex items-start justify-between gap-5"><span className="font-display text-[24px] leading-[1.05] tracking-[-0.03em] transition-colors group-hover:text-dark-olive">{item.title}</span><span className="shrink-0 text-foreground/60 transition-transform group-hover:translate-x-1" aria-hidden="true">↗</span></div><p className="mt-3 text-[11px] text-foreground/60">0{index + 1} · {item.meta}</p></a>)}</div><a id="wiedza" href="#wiedza" className="mt-8 inline-flex items-center text-[13px] font-semibold text-foreground underline decoration-border underline-offset-8 transition-colors hover:decoration-olive">Zobacz bazę wiedzy <span className="ml-3"><Arrow /></span></a></div></div></div></section>

    <section id="oplaty" className="border-t border-border bg-surface"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:py-28 lg:px-8 lg:py-32"><div className="grid gap-10 lg:grid-cols-12 lg:gap-10"><div className="lg:col-span-5"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-olive">06 — Opłaty</p><h2 className="mt-5 max-w-[500px] font-display text-[40px] leading-[0.98] tracking-[-0.04em] sm:text-[52px]">Ile kosztuje czynność notarialna?</h2></div><div className="lg:col-span-6 lg:col-start-7"><p className="max-w-[560px] text-[16px] leading-7 text-foreground/70">Na całkowity koszt mogą składać się m.in.:</p><ul className="mt-7 grid gap-x-8 gap-y-3 border-y border-border py-6 text-[15px] sm:grid-cols-2"><li>Taksa notarialna</li><li>VAT</li><li>Podatki</li><li>Opłaty sądowe</li><li>Wypisy aktu</li></ul><a href="#kontakt" className="mt-8 inline-flex items-center text-[13px] font-semibold text-foreground underline decoration-border underline-offset-8 transition-colors hover:decoration-olive">Sprawdź, od czego zależą opłaty <span className="ml-3"><Arrow /></span></a></div></div></div></section>

    <section id="wizyta" className="border-t border-border"><div id="kontakt" className="mx-auto max-w-[1280px] px-5 py-20 sm:py-28 lg:px-8 lg:py-32"><div className="grid gap-12 lg:grid-cols-12 lg:gap-10"><div className="lg:col-span-5"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-olive">07 — Kontakt</p><h2 className="mt-5 max-w-[500px] font-display text-[48px] leading-[0.95] tracking-[-0.045em] sm:text-[64px]">Umów wizytę.</h2><p className="mt-7 max-w-[420px] text-[16px] leading-7 text-foreground/70">Skontaktuj się z kancelarią, aby ustalić, jakie dokumenty przygotować i znaleźć dogodny termin.</p></div><div className="lg:col-span-6 lg:col-start-7"><dl className="divide-y divide-border border-y border-border">{[contactData.phoneMaria.label, contactData.phoneSara.label, contactData.email.label, contactData.hours].map((item) => <div key={item} className="flex items-center justify-between gap-5 py-5 text-[14px]"><dt>{item}</dt><dd className="text-[11px] uppercase tracking-[0.12em] text-foreground/60">Placeholder</dd></div>)}<div className="flex items-center justify-between gap-5 py-5 text-[14px]"><dt>{contactData.address}</dt><dd className="text-[11px] uppercase tracking-[0.12em] text-foreground/60">Adres</dd></div><div className="flex items-center justify-between gap-5 py-5 text-[14px]"><dt>{contactData.parking}</dt><dd className="text-[11px] uppercase tracking-[0.12em] text-foreground/60">Informacja</dd></div></dl><div className="mt-8 flex min-h-[220px] items-center justify-center border border-dashed border-border bg-secondary/50 text-center" data-map-slot="future-map"><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-olive">Mapa kancelarii</p><p className="mt-3 text-[12px] text-foreground/60">Miejsce na lekką mapę lub wskazówki dojazdu.</p></div></div></div></div></div></section>

    <footer id="polityka-prywatnosci" className="border-t border-border bg-foreground text-surface"><div className="mx-auto max-w-[1280px] px-5 py-14 lg:px-8 lg:py-16"><div className="grid gap-12 sm:grid-cols-2 lg:grid-cols-12 lg:gap-10"><div className="lg:col-span-5"><BrandWordmark href="#top" inverse variant="footer" /></div><nav className="grid grid-cols-2 gap-x-8 gap-y-4 text-[12px] text-surface/70 sm:col-span-1 lg:col-span-6 lg:col-start-7" aria-label="Linki w stopce">{footerLinks.map(([label, href]) => <a key={label} href={href} className="transition-colors hover:text-surface">{label}</a>)}</nav></div><div className="mt-16 flex flex-col justify-between gap-3 border-t border-surface/20 pt-5 text-[10px] text-surface/50 sm:flex-row"><span>Wrocław · Muchobór Wielki</span><span>© Czarniak · Podkówka</span></div></div></footer>
  </>;
}
