"use client";

import { useMemo, useState } from "react";
import { services } from "@/lib/services";

const suggestions = ["Sprzedaję mieszkanie", "Chcę założyć spółkę", "Muszę załatwić spadek"];
function normalize(value: string) { return value.toLocaleLowerCase("pl-PL").normalize("NFD").replace(/[\u0300-\u036f]/g, ""); }

export function ServiceSearch() {
  const [query, setQuery] = useState("");
  const normalizedQuery = normalize(query.trim());
  const results = useMemo(() => { if (!normalizedQuery) return []; return services.filter((service) => normalize([service.title, service.category, ...service.keywords].join(" ")).includes(normalizedQuery)); }, [normalizedQuery]);
  return <div className="mt-10 max-w-[850px]"><label htmlFor="service-search" className="sr-only">Opisz, czego potrzebujesz</label><div className="relative"><input id="service-search" type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="np. sprzedaję mieszkanie / chcę założyć spółkę / sprawa spadkowa" className="min-h-[76px] w-full border-b border-foreground bg-transparent px-0 pr-12 font-display text-[25px] tracking-[-0.02em] outline-none placeholder:text-muted/60 focus:border-olive sm:text-[32px]" autoComplete="off" aria-describedby="search-help search-results" /><span className="pointer-events-none absolute right-1 top-1/2 -translate-y-1/2 text-2xl text-foreground/70" aria-hidden="true">⌕</span></div><p id="search-help" className="mt-4 text-[12px] text-foreground/70">Wpisz nazwę czynności albo opisz ją własnymi słowami.</p><div className="mt-7 flex flex-wrap gap-2" aria-label="Podpowiedzi wyszukiwania">{suggestions.map((suggestion) => <button key={suggestion} type="button" onClick={() => setQuery(suggestion)} className="border border-border px-3 py-2 text-left text-[12px] text-foreground/70 transition-colors hover:border-olive hover:bg-surface hover:text-foreground">{suggestion}</button>)}</div><div id="search-results" aria-live="polite" className="mt-8 min-h-[112px]">{normalizedQuery ? <>{results.length > 0 ? <div className="divide-y divide-border border-y border-border">{results.map((service) => <a href={`#${service.id}`} key={service.id} className="group flex items-start justify-between gap-5 py-4"><span><span className="block text-[10px] uppercase tracking-[0.16em] text-olive">{service.category}</span><span className="mt-1 block font-display text-[23px] leading-tight">{service.title}</span><span className="mt-1 block text-[12px] text-foreground/70">{service.description}</span></span><span className="mt-2 shrink-0 text-foreground/70 transition-transform group-hover:translate-x-1" aria-hidden="true">↗</span></a>)}</div> : <p className="border-y border-border py-5 text-[13px] text-foreground/70">Nie znaleźliśmy jeszcze takiej czynności. Zadzwoń do kancelarii — pomożemy nazwać i przygotować sprawę.</p>}</> : <p className="text-[12px] text-foreground/60">Wyniki pojawią się tutaj po wpisaniu zapytania.</p>}</div></div>;
}
